[package]
name = "fractalify"
version = "0.1.0"
authors = ["Tuomas MÃ¤kinen <tuomas@giantswarm.io>"]
edition = "2018"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
num-complex = "0.4.0"
